### ISSUE TITLE
Inconsistency in the behaviors according to how we write the emoji

### ISSUE THREAD

**Issue by CcileMoul1** [phibr0/obsidian-emoji-shortcodes#10]
I tried to use this plugin by writing the name but it didn't gave the same result according to how I wrote it. I don't really know how to explain it so here is a screenshot of some tests. (left edit, write preview)
In the first case, I insert the emoji after writing the whole sentence.
![Capture d’écran de 2021-08-23 14-16-53](https://user-images.githubusercontent.com/25252932/130445929-aa34ab91-d3eb-479a-9780-1b85c30d663b.png)

I'm using Ubuntu 20.04.2 LTS
Obsidian 0.12.12
Emoji Shortcodes 1.4.0

Thanks
Ccile

I have no idea on how it **should** work but I think I would prefer to have the small picture in both view : edit and preview.
My second choice would be the name in edit and the small picture in preview.

**Comment by phibr0** [comment]
Disable the other Emoji Plugin (or the rendering of Twitter emojis in it's settings)

**Comment by CcileMoul1** [comment]
The other Emoji Plugin was already removed.

**Comment by phibr0** [comment]
Then it doesn't unload properly or something. This definitely is not about this Plugin because it doesn't even bundle these Emojis.

**Comment by phibr0** [comment]
And only the first one worked because it was done by a MarkdownPostProcessor added by this Plugin

**Comment by CcileMoul1** [comment]
I tested it with another vault where I didn't install (and remove) the Emoji Plugin and it works well.
So now, I just have to understand what went wrong with the removing of Emoji Plugin.

Thanks for your answer
