### ISSUE TITLE
Sunglasses :sunglasses: is showing as :dark_sunglasses:  >> Makes me :cry: 

### ISSUE THREAD

**Issue by ahopkins** [phibr0/obsidian-emoji-shortcodes#11]
When I type `:sunglasses:` I expect to see :sunglasses: and not :dark_sunglasses: 

---

Nice work on the plugin BTW. This is a feature that should IMO be standard and is a bit of an oversight that it is not.

**Comment by phibr0** [comment]
I think the Emojilist I am using isn't fully correct nor has all the Emojis.
I need a better json file with alle emoji shortcodes and their respective emoji..

**Comment by ahopkins** [comment]
http://www.unicode.org/emoji/charts/full-emoji-list.html

v13.1
