### ISSUE TITLE
Cannot install version 1.5 from Obsidian

### ISSUE THREAD

**Issue by amrtn** [phibr0/obsidian-emoji-shortcodes#15]
![image](https://user-images.githubusercontent.com/151747/131308452-2372c9ec-a77b-42c1-82f0-e658b057a613.png)

Obsidian version: v.0.12.12 on windows

**Comment by phibr0** [comment]
GitHub Actions currently don't work correctly. The build doesn't go through and thus there are no Release Files..

**Comment by phibr0** [comment]
Works now

**Comment by amrtn** [comment]
It worked! 😄 
Keep up the good work!
