### ISSUE TITLE
Some emojis aren't available

### ISSUE THREAD

**Issue by puffitos** [phibr0/obsidian-emoji-shortcodes#18]
I've noticed that I can't get some emojis to appear, no matter what emoji code I use. 

An example is [large green circle](https://emojipedia.org/large-green-circle/). 
I've used both shortcodes suggested in the above page, but it doesn't render and/or appear on the suggestion droplist.

![image](https://user-images.githubusercontent.com/52347078/132940708-451df14d-2b16-41e4-a289-43f03c271b42.png)

Unfortunately housamz json with the emojis isn't complete and I would like my circles to be super colorful.
Is it ok if I just add them to the `emojiList.ts` and add a pull request? :)

**Comment by phibr0** [comment]
> Unfortunately housamz json with the emojis isn't complete and I would like my circles to be super colorful.
Is it ok if I just add them to the emojiList.ts and add a pull request? :)

If you use uniform and correct short codes yes, I would rather find a complete emoji list though... I didn't have any luck with that

**Comment by klieret** [comment]
Hmm, we could web scrape emojipedia in the worst case, right? 
I just teid out https://github.com/bcongdon/python-emojipedia, but it's a bit broken (it can retrieve all emojis, but currently doesn't show the shortcodes, so it might need some fixing)

**Comment by puffitos** [comment]
The new update seems to include much more emojis. The green square I was looking for is definitely there :)
