### ISSUE TITLE
1.0.0: Seems emojis with underscore don’t work

### ISSUE THREAD

**Issue by Moonbase59** [phibr0/obsidian-emoji-shortcodes#2]
(EDIT: See below) ~~I like the immediate replace against a Unicode char, even in edit mode.~~ Another useful one, thanks!

For some reason, emojis using an underscore in their name don’t work, try:

```
:purple_heart:
:broken_heart:

😀
:woman_bowing:
```

Maybe CM hits in, thinking an _italicized_ word is coming?

I’ll still have to try in a naked vault, results in a moment.

**EDIT:** It’s the same in a new vault, with no other community plugins installed.
Using Obsidian 0.12.12, installer 0.12.10, on Linux (AppImage).

**Comment by phibr0** [comment]
The Plugin doesn't immediately change the Short code to Unicode. That has to some Feature of another Program/your Distro.

The Plugin is literally just a `MarkdownPostProcessor`.

**Comment by phibr0** [comment]
Do the Emojis with underscores show correctly in Preview Mode?

**Comment by Moonbase59** [comment]
As just talked about in [Discord](https://discord.com/channels/686053708261228577/707816848615407697/874319595698286612), it was my fault: I had the _Espanso_ text expander running, and the emoji pack is installed. Sorry for that confusion!

Still, having switched off _Espanso_ now, in the preview those with underscores don’t get replaced:

![Auswahl_183](https://user-images.githubusercontent.com/3706922/128737304-13c961bb-ac4e-4847-b54a-31abc325e0fb.png)

**Comment by phibr0** [comment]
Hm thats weird. I can't reproduce this as they work for me.

![image](https://user-images.githubusercontent.com/59741989/128837266-e4714092-d375-4c7d-989c-03b87ff23af4.png)

![image](https://user-images.githubusercontent.com/59741989/128837285-aebb1d98-e8d7-4ff7-93bd-c4d41ee205bf.png)

**Comment by Moonbase59** [comment]
I don’t know what’s happening here. Yesterday it didn’t work, to day it does (sort of).

Maybe some interfering plugin updated or whatever. Frustrated today. Let’s just close this issue.

_Today’s_ result:

Laptop, fresh vault:

![Auswahl_184](https://user-images.githubusercontent.com/3706922/128864067-432f8779-9a8c-451f-8dee-b92135aea9d4.png)

Laptop, my vault:

![Auswahl_185](https://user-images.githubusercontent.com/3706922/128864305-7c028059-ac83-4a91-a861-05cdcd55d8d7.png)

(Strict line ends set differently, so ok)

Desktop:

![Auswahl_119](https://user-images.githubusercontent.com/3706922/128864615-4ef02529-4bd6-4468-98a2-d3d0895bdb28.png)
