### ISSUE TITLE
Specify shortcode convention

### ISSUE THREAD

**Issue by klieret** [phibr0/obsidian-emoji-shortcodes#20]
First of all, great addon!

I was wondering which convention you follow for the codes. I know at least three of them: github, slack, emojipedia. This would be very useful information to be added to the readme.

I am also asking because I wanted to add some missing emojis, such as the shrugging ones #18 and there the codes are all distinct.

**Comment by phibr0** [comment]
You can see the whole List here: https://github.com/phibr0/obsidian-emoji-shortcodes/blob/master/src/emojiList.ts
I really don't know which convention it is, I grabbed the List of of here: https://gist.githubusercontent.com/housamz/67087a81eaf78837a420fdef4accf263/raw/8c6a8bd28af5431f8ad394d433bd2ae201ec4bf9/emojis.json

**Comment by phibr0** [comment]
If you can find a better, more complete List that would be great.

**Comment by klieret** [comment]
Hmm, we could web scrape emojipedia in the worst case, right? 
I might try out https://github.com/bcongdon/python-emojipedia today, this seems to already provide an interface to emojipedia.
