### ISSUE TITLE
Missing modifier characters in YAML frontmatter

### ISSUE THREAD

**Issue by OfficerHalf** [phibr0/obsidian-emoji-shortcodes#22]
Using `:heavy_check_mark:` in YAML frontmatter should render (U+2714, U+FE0F), but seems to only be rendering the first character. Using it anywhere in the normal editor renders it correctly. If adding the emoji using another method both characters are rendered, and it appears correctly as ✔️.

**Comment by OfficerHalf** [comment]
This doesn't seem to be the case with all emoji made from multiple characters `:person_curly_hair:` 🧑‍🦱 seems be added correctly.

**Comment by phibr0** [comment]
Might be that your Font doesn't show the Emoji Correctly. The Plugin shouldn't differentiate in what type of block it's in.

**Comment by OfficerHalf** [comment]
I don't think it's a font thing:
![Checkmark](https://user-images.githubusercontent.com/4851889/134785926-088bfadc-d6de-4e97-ab2b-f7672b095c5c.gif)

**Comment by phibr0** [comment]
> Using it anywhere in the normal editor renders it correctly.

Are you sure?
For me it will always be the black and white, singe character, Version

**Comment by OfficerHalf** [comment]
However it seems to be an issue with obsidian - not your plugin. The same behavior happens when you copy and paste the emoji into the frontmatter. Feel free to close this.

**Comment by OfficerHalf** [comment]
> 
> 
> > Using it anywhere in the normal editor renders it correctly.
> 
> Are you sure?
> For me it will always be the black and white, singe character, Version

Maybe it's a platform thing then? It definitely works in the editor for me. Tried with the default theme too.

**Comment by phibr0** [comment]
You could try the new Editor in the latest Obsidian Version. It might fix some stuff.

I will close this for now.
