### ISSUE TITLE
Emoji Suggester inside [[links]] and in file title? 

### ISSUE THREAD

**Issue by Akimaru666** [phibr0/obsidian-emoji-shortcodes#25]
Hi,

I use a lot of emoji to indicate the type of note, 👀 for human , 📚 for book and so on, and when I try to type ":eyes:" inside [[]], I don't get any suggestion, neither in the title bar.

Thanks for all

**Comment by phibr0** [comment]
Unfortunately, this is not possible, while you type a link (`[[]]`) the note suggestion box has priority and the file title is not part of the note editor.

If you use Windows you can use: `Win` + `.`
