### ISSUE TITLE
The suggestion bar will not disappear in editor mode (legacy mode)

### ISSUE THREAD

**Issue by shaggyfeng** [phibr0/obsidian-emoji-shortcodes#27]
If the new live preview version does not work well with the legacy mode. Is it possible that the user can select which version to use in the plugin setting?

**Comment by phibr0** [comment]
Hmm, I didn't change anything regarding the new Editor. 
Can you send a Screenshot of your problem?

**Comment by shaggyfeng** [comment]
> Hmm, I didn't change anything regarding the new Editor. Can you send a Screenshot of your problem?

Well, It turns out to be a problem with the natural language date plugin's bug. Once I disable its suggestion menu function, the emoji shortcut plugin works just fine. Thanks
