### ISSUE TITLE
An emoticon image appears in the preview mode

### ISSUE THREAD

**Issue by coolkidsneversleep** [phibr0/obsidian-emoji-shortcodes#28]
![image](https://user-images.githubusercontent.com/80826587/149606516-720f289d-c9d4-49b2-ba61-8995c45aa10d.png)
Thank you for developing it. However, can you modify the emoticon image that appears in the preview mode so that it does not appear?

**Comment by phibr0** [comment]
The Emoji Images are from a different Emoji Plugin. I believe you can disable them in its settings. See  #17
