### ISSUE TITLE
Think it possible to add an "Emoji Matcher" like on the Discord?

### ISSUE THREAD

**Issue by Moonbase59** [phibr0/obsidian-emoji-shortcodes#3]
Would you think it feasible to add an "emoji matcher" that opens a fuzzy match suggester as soon as one starts typing `:…`?

![Auswahl_182](https://user-images.githubusercontent.com/3706922/128735890-ae0d72b3-6daa-4a25-a20c-5063f65344f2.png)

**Comment by phibr0** [comment]
I would really like this Feature, unfortunately I still haven't figured out how to do stuff like this. I had these Suggesters planned for other Plugins too but in the End just used Obsidians normal FuzzySuggestModals

**Comment by konhi** [comment]
[Emoji Toolbar](https://github.com/oliveryh/obsidian-emoji-toolbar) has emoji picker like that for possible code reference.

![image](https://user-images.githubusercontent.com/61631665/129487701-fbdd775a-7b50-41d6-bf69-2313c19057ff.png)

**Comment by phibr0** [comment]
Thats just Obsidians Default FuzzySuggestModal, the Problem is to put that into a PopOver for the Editor.

**Comment by konhi** [comment]
What about it? https://github.com/argenos/nldates-obsidian

**Comment by phibr0** [comment]
That looks exactly like what is needed. I will look into it
