### ISSUE TITLE
There is no ❤️ emoji

### ISSUE THREAD

**Issue by bpdoto** [phibr0/obsidian-emoji-shortcodes#32]
The standard red heart aka ```:heart:``` is not supported.

**Comment by aziham** [comment]
@bpdoto I updated the `:heart:` shortcode's emoji. The issue will be fixed once @phibr0  merge my PR #39

**Comment by makew0rld** [comment]
@phibr0 @aziham I am still seeing this issue with 2.2.0 installed. Typing `:heart:` does not do anything.
