### ISSUE TITLE
Can't be used with dataview inline fields

### ISSUE THREAD

**Issue by konhi** [phibr0/obsidian-emoji-shortcodes#5]
Shortcodes can't be used with [dataview](https://blacksmithgu.github.io/obsidian-dataview/) inline field (key:: value)

- **Editor mode**

![image](https://user-images.githubusercontent.com/61631665/129483404-bb5788d0-fa58-4666-a683-51c64ba3df0a.png)

- **Result**

![image](https://user-images.githubusercontent.com/61631665/129483413-f34e6f49-afe2-427b-aa3c-85f2672048bb.png)

- **Desired result**

![image](https://user-images.githubusercontent.com/61631665/129483422-7524fe94-3b2e-4270-a03e-0d1ab124ea15.png)

**Comment by phibr0** [comment]
You could turn on immediate Replace in the Settings. That should fix your Problem, but I am not sure if that is what you want

**Comment by konhi** [comment]
Thanks for replying! It doesn't solve the issue, because it isn't possible to use emoji in dataview query (thought of course it may be fixed somehow) - that's why I want to use this plugin.
I made a pull request that solves this issue.

**Comment by phibr0** [comment]
Merged your PR, thank you!
