### ISSUE TITLE
Can't emoji shortcodes in the browse section

### ISSUE THREAD

**Issue by johnny-liaw** [phibr0/obsidian-emoji-shortcodes#9]
Hi, 

Thanks for making this plugin! I was trying to install it from the `Browse` section from setting but it says 'no results found'. Just wondering if you have any idea why that is, I found it quite strange 🤔 

![image](https://user-images.githubusercontent.com/18642522/130439541-0cd8a91c-10f4-4406-8c32-80fb536f9039.png)

**Comment by phibr0** [comment]
See #7 Please
